name: Build, Lint, and Test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn
      - run: yarn build
      - run: yarn format:check
      - run: yarn test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
